name: Dockerfile

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Build, test Dockerfile
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run docker image
      run: |
        docker build -t bioslam -f ./docker/ubu-20.Dockerfile ./docker
        docker run -id --name bioslam bioslam

    - name: Run tests
      run: docker exec -i bioslam make test
